brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path
from todos.views import (
    TodoListView,
    TodoDetailView,
    TodoCreateView,
    TodoUpdateView,
    TodoDeleteView,
    TodoItemCreateView,
    TodoItemUpdateView,
)

urlpatterns = [
    path("", TodoListView.as_view(), name="todo_list_list"),
    path("<int:pk>/", TodoDetailView.as_view(), name="todo_list_detail"),
    path("create/", TodoCreateView.as_view(), name="todo_list_create"),
    path("<int:pk>/edit/", TodoUpdateView.as_view(), name="todo_list_update"),
    path(
        "<int:pk>/delete/",
        TodoDeleteView.as_view(),
        name="todo_list_delete"
    ),
    path(
        "items/create/",
        TodoItemCreateView.as_view(),
        name="todo_item_create"
    ),
    path(
        "items/<int:pk>/edit/",
        TodoItemUpdateView.as_view(),
        name="todo_item_update"
    )
]

todos/models.py
from django.db import models


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(
        null=True,
        blank=True,
        auto_now=False,
        auto_now_add=False
    )
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList",
        related_name="items",
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.task

todos/views.py
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from todos.models import TodoItem, TodoList


class TodoListView(ListView):
    model = TodoList
    template_name = "list.html"
    paginate_by = 20


class TodoDetailView(DetailView):
    model = TodoList
    template_name = "detail.html"


class TodoCreateView(CreateView):
    model = TodoList
    template_name = "create.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoUpdateView(UpdateView):
    model = TodoList
    template_name = "edit.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.id])


class TodoDeleteView(DeleteView):
    model = TodoList
    template_name = "delete.html"
    success_url = reverse_lazy("todo_list_list")


class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "itemcreate.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "itemedit.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("todo_list_detail", args=[self.object.list.id])

todos/templates/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Todo Lists</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Create a new list</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" value="Create">Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

todos/templates/delete.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Todo Lists</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Are you sure?</h1>
                <h2>This will delete the list: {{ todolist.name }}.</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" value="Delete">Delete</button>
                </form>
            </div>
        </main>
    </body>
</html>

todos/templates/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>TodoLists</title>
    </head>
    <body>
        <main>
            <div>
                <h1>{{ todolist.name }}</h1>
                <p>
                    <a href="{% url 'todo_list_update' todolist.pk %}">Edit</a>
                </p>
                <p>
                    <a href="{% url 'todo_list_delete' todolist.pk %}">Delete</a>
                </p>
                <h2>Tasks</h2>
                <table>
                    <thead>
                        <th>Task</th>
                        <th>Due Date</th>
                    </thead>
                    <tbody>
                        {% for item in todolist.items.all %}
                            <tr>
                                <td>
                                    <a href="{% url 'todo_item_update' item.pk %}">{{ item.task }}</a>
                                </td>
                                <td>{{ item.due_date }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </main>
    </body>
</html>

todos/templates/edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Todo Lists</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Update {{ todolist.name }}</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" value="Update">Update</button>
                </form>
            </div>
        </main>
    </body>
</html>

todos/templates/itemcreate.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Todo Lists</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Create a new item</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" value="Create">Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

todos/templates/itemedit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Todo Lists</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Update Item</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" value="Update">Update</button>
                </form>
            </div>
        </main>
    </body>
</html>

todos/templates/list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Todo Lists</title>
    </head>
    <body>
        <main>
            <div>
                <h1>My Lists</h1>
                <p>
                    <a href="{% url 'todo_list_create' %}">Create a new list</a>
                </p>
                <p>
                    <a href="{% url 'todo_item_create' %}">Create a new item</a>
                </p>
                <table>
                    <thead>
                        <th>Name</th>
                        <th>Number of items</th>
                    </thead>
                    <tbody>
                        {% for list in todolist_list %}
                            <tr>
                                <td>
                                    <a href="{% url 'todo_list_detail' list.pk %}">{{ list.name }}</a>
                                </td>
                                <td>{{ list.items.all|length }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </main>
    </body>
</html>